// ===----------------------------------------------------------------------===
//
// This source file is part of the Amethyst Vein open source project
//
// Copyright (c) 2026 Mia Koring.
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.
//
// ===----------------------------------------------------------------------===

import Foundation
import SQLiteDB

struct PersistedFieldDTO: Sendable {
    let key: String
    let id: ULID
    let schema: String
    let sqliteType: SQLiteTypeName
    let enclosingObjectID: ObjectIdentifier
}

/// Information about a field. Only intended to be generated by the `@Model` macro and consumed by Vein.
public struct FieldInformation: Sendable {
    let typeName: SQLiteTypeName
    let key: String
    let eagerLoaded: Bool
    let relationshipToType: (any PersistentModel.Type)?

    public nonisolated init(
        _ typeName: SQLiteTypeName,
        _ key: String,
        _ eagerLoaded: Bool,
        _ relationshipToType: (any PersistentModel.Type)? = nil
    ) {
        self.typeName = typeName
        self.key = key
        self.eagerLoaded = eagerLoaded
        self.relationshipToType = relationshipToType
    }
}

extension FieldInformation: Hashable {
    public static func == (lhs: FieldInformation, rhs: FieldInformation) -> Bool {
        lhs.typeName == rhs.typeName && lhs.key == rhs.key
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(typeName)
        hasher.combine(key)
    }
}

extension [FieldInformation] {
    var eagerLoaded: [FieldInformation] {
        self.filter(\.eagerLoaded)
    }
}

extension FieldInformation {
    package var fetchExpressible: Expressible {
        return switch typeName.isNull {
            case true:
                switch SQLiteTypeName.notNull(typeName) {
                    case .integer: SQLExpression<Int64?>(key)
                    case .real: SQLExpression<Double?>(key)
                    case .text: SQLExpression<String?>(key)
                    case .blob: SQLExpression<Data?>(key)
                    case .jsonb: SQLExpression<String?>(literal: "json(\"\(key)\")")
                    default:
                        fatalError(
                            "Unexpectedly found null. Check SQLiteTypeName.notNull() for logic errors"
                        )
                }
            case false:
                switch typeName {
                    case .integer: SQLExpression<Int64>(key)
                    case .real: SQLExpression<Double>(key)
                    case .text: SQLExpression<String>(key)
                    case .blob: SQLExpression<Data>(key)
                    case .jsonb: SQLExpression<String>(literal: "json(\"\(key)\")")
                    default:
                        fatalError(
                            "Unexpectedly found null. Check SQLiteTypeName.notNull() for logic errors"
                        )
                }
        }
    }

    package func addRetroactively(to schema: String, on context: ManagedObjectContext) throws {
        switch SQLiteTypeName.notNull(typeName) {
            case .integer:
                try context.run(
                    Table(schema).addColumn(SQLExpression<Int64?>(key))
                )
            case .real:
                try context.run(
                    Table(schema).addColumn(SQLExpression<Double?>(key))
                )
            case .text:
                try context.run(
                    Table(schema).addColumn(SQLExpression<String?>(key))
                )
            case .blob, .jsonb:
                try context.run(
                    Table(schema).addColumn(SQLExpression<Data?>(key))
                )
            case .null:
                fatalError(
                    "Unexpectedly found null. Check SQLiteTypeName.notNull() for logic errors"
                )
        }
    }
}
