import Foundation
import ULID
import Logging

/// The primary key of a ``PersistentModel``.
///
/// This property wrapper gets autogenerated by the `@Model` macro.
/// You can set an id while it is not managed by a ``ManagedObjectContext``.
/// That can be helpful for migrations for example. Once managed, sets are ignored.
@propertyWrapper
public class PrimaryKey: PersistedField, @unchecked Sendable {
    static let logger = Logger(label: "Vein PrimaryKey")
    public typealias WrappedType = ULID
    
    public var _key: String? {
        get {
            "id"
        }
        set {}
    }
    
    private let lock = NSLock()
    
    private var store: ULID
    
    public var wasTouched = false
    
    /// Only set during migrations to preserve old ID
    /// Must be set before inserting new Model into context
    public var wrappedValue: ULID {
        get {
            lock.withLock({
                return store
            })
        }
        set {
            lock.withLock {
                if let context = model?.context {
                    if context.modelContainer.logConfiguration.primaryKeyMutation {
                        PrimaryKey.logger.warning("""
                        Attempted to mutate ID of inserted model with ID: \(store). \
                        This is not supported.
                        """)
                    }
                } else {
                    store = newValue
                }
            }
        }
    }
    
    public var isLazy: Bool {
        false
    }
    
    public static var sqliteTypeName: SQLiteTypeName {
        UUID.sqliteTypeName
    }
    
    public weak var _model: (any PersistentModel)?
    
    public init(wrappedValue: ULID = ULID()) {
        self.store = wrappedValue
    }
    
    /// No-op: Primary key is immutable after insertion and doesn't participate in rollback.
    public func _setStoreToCapturedState(_ state: Any) {}
    
    public var _persistableValue: ULID {
        get { self.wrappedValue }
        set { self.wrappedValue = newValue }
    }
    
    // Connect model instance to wrapper.
    public static subscript<OuterSelf: PersistentModel>(
        _enclosingInstance observed: OuterSelf,
        wrapped wrappedKeyPath: ReferenceWritableKeyPath<OuterSelf, ULID>,
        storage storageKeyPath: ReferenceWritableKeyPath<OuterSelf, PrimaryKey>
    ) -> ULID {
        get {
            var storage = observed[keyPath: storageKeyPath]
            storage.lock.withLock {
                if storage.model == nil {
                    storage.model = observed
                }
            }
            return storage.wrappedValue
        }
        set {
            var storage = observed[keyPath: storageKeyPath]
            storage.lock.withLock {
                if storage.model == nil {
                    storage.model = observed
                }
            }
            storage.wrappedValue = newValue
        }
    }
}
