name: Swift Test (Ubuntu 24.04)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  linux:
    runs-on: blacksmith-8vcpu-ubuntu-2404-arm
    container:
      image: swift:6.3.2-noble
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #6.0.2
        with:
          persist-credentials: false
      - name: Test
        # Disable encryption for testing purposes if needed
        run: ./Scripts/tsan-test.sh
